### ISSUE TITLE
append hostname as part of filename

### ISSUE THREAD

**Issue by dano3006** [openbsm/openbsm#1]
Currently OpenBSM creates the standard filename in the format yyyymmddhhmmss.yyyymmddhhmmss. This is fine for standalone machines, but in modern environments where multiple machines on a network have their logs collected by a log aggregator, appending the hostname for identification would be a significant improvement, e.g. yyyymmddhhmmss.yyyymmddhhmmss.hostname. 
(Note that BSM on Solaris has been doing this since its creation.)

**Comment by rwatson** [comment]
"Works for me" -- but you need to have a "host: foo" line in /etc/security/audit_control?

**Comment by dano3006** [comment]
Will that work in the current configuration of the audit_control config file or is that an additional feature request?

**Comment by rwatson** [comment]
I am using it on several FreeBSD 9.3 machines today, so already present. I guess the question is whether we might want to include a hostname even if the "host:" parameter isn't set -- I think the reason we ended up with this model is that for DHCP-configured systems, the hostname may in fact not be set until long after auditd starts...

**Comment by rwatson** [comment]
I wonder if you could confirm that you were able to find and use the feature? If so, I'll close this bug report. (I'm not sure what FreeBSD version the feature first appeared in -- and I'm uncertain if the current Mac OS X version includes it. When we next ship an OpenBSM release, it would be worth prodding Apple to update.)

**Comment by staceyson** [comment]
On Mac OS X adding "host:hostname" to /etc/security/audit_control does create audit trails in the form of  yyyymmddhhmmss.yyyymmddhhmmss.hostname.

**Comment by dano3006** [comment]
This feature works in OSX 10.9.5 and 10.11.x (unreleased, development beta).

I have not tested it in 10.10.x yet. Obviously it probably does work. If I get a virtual machine of 10.10 stood up I will test and reply.

**Comment by rwatson** [comment]
OK, sounds like we're 'all good' in terms of the feature, then, so marking closed. If some refinement would be useful, do feel free to open a further issue.
