### ISSUE TITLE
audit_set_qsize() could not parse audit_control(5) file: Invalid argument

### ISSUE THREAD

**Issue by arunthomas** [openbsm/openbsm#5]
In FreeBSD 11.0-BETA1, I see the following error when I start auditd and audit_control has no qsize entry:

```
audit_set_qsize() could not parse audit_control(5) file: Invalid argument
```

When I set qsize in audit_control, the error goes away. Is the qsize parameter required? It seems qsize has a default value, so possibly the configuration entry could be optional?

**Comment by cbrueffer** [comment]
Hi Arun, was this with the stock system auditd, a newer version from GitHub, or a modified version? Just wondering, since @rwatson added the qsize functionality after your report. Am I missing something?

**Comment by cbrueffer** [comment]
I can reproduce the error with the current code though. Robert, what would be a good default value for this?

**Comment by rwatson** [comment]
I think that the preferred behaviour would be to not set a kernel queue size, accepting the kernel default, if nothing is specified. So perhaps we need a 'magic' value, such a -1, to capture the idea that ```auditd(8)``` shouldn't frob the kernel queue-size setting?

**Comment by cbrueffer** [comment]
Yeah, sounds sane.

**Comment by cbrueffer** [comment]
The following patch fixes the issue in my testing: https://github.com/cbrueffer/openbsm/commit/1f68f9849be7974077ff475b0e8f897500588452

**Comment by rwatson** [comment]
I believe this issue (or a closely related one) also applies to the ```host``` field, which should be optional.

**Comment by rwatson** [comment]
@cbrueffer: I wonder if that patch also needs to fix any type-related stuff in ```openbsm/tools/audump.c```? It looks like it also assumes that the queue-size variable is a ```long```, whereas in fact it is an ```int```.

**Comment by arunthomas** [comment]
Thanks, Christian. The patch works for me.

**Comment by cbrueffer** [comment]
Thanks for testing! @rwatson good point, I added this in the final patch. I'll have a look at the host field as well.
