### ISSUE TITLE
Empty naflags causes parse error

### ISSUE THREAD

**Issue by arunthomas** [openbsm/openbsm#6]
I would like to have the audit framework running, but I do not want to write any audit entries to disk. When I set naflags to empty, I receive the following error when starting auditd:

```
auditd_set_namask() could not parse audit_control(5) file: Invalid argument
```

Is there a better way to do this? I am running  FreeBSD 11.0-BETA1,

**Comment by rwatson** [comment]
This patch looks like it does the trick here, by enabling support for variables in ```/etc/security/audit_control``` that are named but have no value (including ```naflags``` and ```flags```): https://gist.github.com/rwatson/fd661fe0e0cec3f66babae9b8d5243e6

**Comment by rwatson** [comment]
Tagging @gvnn3 as he has encountered this issue as well.

**Comment by rwatson** [comment]
I have committed a tweak to FreeBSD's ```/usr/bin/login``` that clarifies the warning message to indicate that the failure is in calculating, rather than setting, the audit mask (r309326), to help future diagnostics in this general area (as relates to having an empty ```flags``` rather than ```naflags```).

**Comment by rwatson** [comment]
Close this issue as it is now believed addressed.

**Comment by rwatson** [comment]
Actually close the issue!
