### ISSUE TITLE
All execve calls are reported as failed

### ISSUE THREAD

**Issue by ltning** [openbsm/openbsm#67]
On FreeBSD, we see the following type of result for all execve() calls in the audit logs:
```
header_ex,130,11,execve(2),0,10.10.2.10,Mon Sep  7 19:34:14 2020, + 851 msec
exec arg,ls,-latr
path,/bin/ls
attribute,555,root,0,76172115,197462,2160727046
subject,ltning,root,0,root,0,60481,58530,14420,192.168.127.2
return,failure: Unknown error: 201,4294967295
trailer,130
```

Not sure where to raise this; here or in FreeBSD bugs. Starting here..

**Comment by csjayp** [comment]
Yes you are in the right place. Are you seeing this in FreeBSD or in a fresh OpenBSM build?

**Comment by ltning** [comment]
Good to know I'm not lost ;)
Like in the other issue I just raised, this is freebsd 12.1.

**Comment by ltning** [comment]
I've raised a bug on this in FreeBSD, and poked again now since nothing seems to have happened for 12.2 (granted, I have not tested this, but this is such a serious issue it should have resulted in a patch release IMO): https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249179

**Comment by bsdtrhodes** [comment]
Hi,
In the FreeBSD bug report, you mentioned this happening in jails. Is it happening only in jails or both inside and outside of jails?

**Comment by ltning** [comment]
No, my reference to jails was, I think(?), the unknown BSM events or something like that. I have confirmed today that this particular problem appears no matter if the event takes place in- or outside of a jail.

**Comment by csjayp** [comment]
Hello, it turns out this was actually a kernel issue that has been fixed:

```
A commit references this bug:

Author: kevans
Date: Sat Oct 24 14:39:18 UTC 2020
New revision: 367002
URL: https://svnweb.freebsd.org/changeset/base/367002

Log:
  audit: correct reporting of *execve(2) success

  r326145 corrected do_execve() to return EJUSTRETURN upon success so that
  important registers are not clobbered. This had the side effect of tapping
  out 'failures' for all *execve(2) audit records, which is less than useful
  for auditing purposes.

  Audit exec returns earlier, where we can know for sure that EJUSTRETURN
  translates to success. Note that this unsets TDP_AUDITREC as we commit the
  audit record, so the usual audit in the syscall return path will do nothing.

  PR:		249179
  Reported by:	Eirik Oeverby <ltning-freebsd anduin net>
  Reviewed by:	csjp, kib
  MFC after:	1 week
  Sponsored by:	Klara, Inc.
  Differential Revision:	https://reviews.freebsd.org/D26922

Changes:
  head/sys/compat/freebsd32/freebsd32_misc.c
  head/sys/kern/kern_exec.c
  head/sys/kern/subr_syscall.c
```

**Comment by csjayp** [comment]
Thanks for the report

**Comment by rwatson** [comment]
Should we be requesting an errata patch for recent 12.x releases once this hits -STABLE?

**Comment by ltning** [comment]
That was the idea, I think. @allanjude mentioned that in another conversation we had about this. Would surely be appreciated by those of us who depend on this and follow releases strictly.

**Comment by kevans91** [comment]
> Should we be requesting an errata patch for recent 12.x releases once this hits -STABLE?

Definitely- I'm going to MFC it in ~2 days and submit the EN template.

**Comment by rwatson** [comment]
Excellent, thanks!

There's probably something important to think about here in terms of having audit tests in the regression suite ...

**Comment by kevans91** [comment]
We do have some in ^/tests/sys/audit that get ran as part of ci.freebsd.org, but IIRC the coverage is not great (as can probably be seen by the fact that it should've failed three years ago when something as basic as *execve became effectively unauditable)

**Comment by csjayp** [comment]
Strong +1 to getting more robust unit testing worked in our CI builds. We
probably want to replace Travis, or add cirrius CI since they will allow us
to do native FreeBSD builds. Kyle and I were discussing this briefly on IRC
the other day.
